

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FrontToBack.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AlstarEntities : DbContext
{
    public AlstarEntities()
        : base("name=AlstarEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Slider> Sliders { get; set; }

    public virtual DbSet<About> Abouts { get; set; }

    public virtual DbSet<Parallax1> Parallax1 { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<AdminSetting> AdminSettings { get; set; }

}

}

